name: Assignment Build And Test

on:
  push:
    branches: [ Lecture* ]
  pull_request:
    branches: [ Lecture* ]

jobs:
  build:
    defaults:
      run:
        working-directory: ./UserGroup/
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Get Directory
      run: pwd

    - name: npm install
      working-directory: ./UserGroup/src/UserGroup.Web/
      run: npm install
    - name: npm build
      working-directory: ./UserGroup/src/UserGroup.Web/
      run: npm run build:prod

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: List Files in Share Views directory
      working-directory: ./UserGroup/src/UserGroup.Web/
      run: ls ./Views/Shared

    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Verify Build Badge
      run: |
        echo "This is a test"
        Write-Host "This is another test"
        Get-Item README.md
